### ISSUE TITLE
Probleme mit Tastaturlayout der GRUB-2-Konsole anpassen

### ISSUE THREAD

**Issue by thoschworks** [ingank/Linux#6]
Hallo,

bei mir läuft das Umstellen des Tastaturlayouts nicht so wie gewünscht. Beim Erstellen des Tastaturlayouts erscheinen mehrere Meldungen:

```
root@t500:~# grub-kbdcomp -o /boot/grub/layouts/de.gkb de
WARNING: Unknown X keysym "dead_belowmacron"
WARNING: Unknown X keysym "dead_belowmacron"
WARNING: Unknown X keysym "dead_belowmacron"
WARNING: Unknown X keysym "dead_belowmacron"
Ungültiger Bezeichner für Tastaturscan Meta_Tab
Ungültiger Bezeichner für Tastaturscan Meta_Tab
Ungültiger Bezeichner für Tastaturscan KP_Comma
Ungültiger Bezeichner für Tastaturscan KP_Comma
Ungültiger Bezeichner für Tastaturscan KP_Comma
Ungültiger Bezeichner für Tastaturscan KP_Comma
Ungültiger Code für Tastaturscan 0x54
Ungültiger Code für Tastaturscan 0x65
Ungültiger Code für Tastaturscan 0x7f
```

Alle weiteren Schritte verlaufen kommentarlos.

Ich wollte das Layout umstellen, damit bei der Eingabe der LUKS-Passphrase die "passende" Tastatur vorhanden ist. Das hat aber nicht geklappt.

**Comment by ingank** [comment]
@thoschworks hallo zurück,

trotz der Warnmeldungen: wurde das Tastaturlayout in der *GRUB-Konsole* umgestellt?
Ich meine in erster Linie die für Passwörter wichtigen Tasten z, y, ä, ö, ü, ß sowie die Sonderzeichen über den Zahlen und die Zeichen Punkt, Komma, Doppelpunkt und Apostroph.

Wenn dem so ist, dann ist an dem Tutorial grundsätzlich nichts auszusetzen.

Auf der anderen Seite bedeutet das nicht, dass LUKS keine Probleme machen könnte...

* https://forum.ubuntuusers.de/topic/cryptsetup-tastaturlayout/
* https://www.linuxmintusers.de/index.php?topic=46557.0

**Comment by thoschworks** [comment]
Hallo @ingank,

Danke für die Rückmeldung und die beiden Links. Ich wollte nicht in Frage stellen, dass Deine Anleitung zutreffend ist. Bevor ich Deiner Anleitung gefolgt bin, habe ich die beiden von Dir verlinkten Seiten gelesen und die von Dir beschriebene Vorgehensweise dort nachvollziehen können. Das hätte ich vielleicht klarer zum Ausdruck bringen sollen. Sorry, wenn dieser falsche Eindruck entstanden ist.

Ich wollte vielmehr nachfragen, ob Du diese Meldungen kennst und vielleicht weitergehende Informationen hast.

Mittlerweile gehe ich davon aus, dass die Umstellung der Tastatur erst nach der Passworteingabe erfolgt.

Wenn das Passwort – warum auch immer – falsch eingegeben wird, dann landet man in der Rescue-Konsole(?). Auch dort ist das Tastaturlayout weiterhin amerikanisch.

Wenn das Passwort korrekt eingegeben ist, dann kann ich im Menü mit den Cursor-Tasten navigieren und mit \<c\> bzw. \<e\> in den jeweiligen Modus springen. Dort funktioniert die Tastatureingabe denn aber **nicht** mehr; also keine falsches Layout, sondern **gar keine** Reaktion auf die Tastaturanschläge.

Ich habe zwischenzeitlich das Passwort in "amerikanischer Tipweise" in einem weiteren Slot eingegeben, sodass es "passt",  so wie es auch in einem der beiden Links aus Deiner Antwort beschrieben ist. Damit ist das eigentliche Problem umgangen.

Nochmals Danke

Thomas

**Comment by ingank** [comment]
@thoschworks :)

Danke für die ausführliche Antwort. Auch wenn du das Thema schon geschlossen hast, möchte ich dir doch gerne antworten.

> Ich wollte vielmehr nachfragen, ob Du diese Meldungen kennst und vielleicht weitergehende Informationen hast.

OK, ich kann mich vage daran erinnern, dass es ein paar 'WARNINGS' gab, doch als bei mir das Ergebnis in GRUB letztendlich zufriedenstellend war, hab ich nicht viel darauf gegeben. Wie gesagt, bei mir hat sich die Fehlerausgabe auf Warnings beschränkt.

> Wenn das Passwort – warum auch immer – falsch eingegeben wird, dann landet man in der Rescue-Konsole(?). Auch dort ist das Tastaturlayout weiterhin amerikanisch.

Leider kenne ich den Bootvorgang mit eingerichtetem LUKS nicht und eine Rescue-Konsole ist mir bis dato auch nicht in die Quere gekommen, wenn ich dein Fragezeichen richtig deute...

> Wenn das Passwort korrekt eingegeben ist, dann kann ich im Menü mit den Cursor-Tasten navigieren und mit <c> bzw. <e> in den jeweiligen Modus springen. Dort funktioniert die Tastatureingabe denn aber nicht mehr; also keine falsches Layout, sondern gar keine Reaktion auf die Tastaturanschläge.

Bedeutet das, dass nach einer erfolgreichen Entsperrung einer Partition Linux REBOOTET und du wieder im GRUB landest? Wenn dem so wäre, und GRUB in diesem Fall nicht 'normal' reagiert, dann wäre dies ein Sonderfall, der auf alle Fälle Wert wäre näher zu betrachten.

---

Danke auf alle Fälle für deine Bemühungen - ich würde gern mehr über LUKS erfahren.
Kannst du mir bitte noch nähere Angaben über deine Distro machen und im Groben darüber, welche Partition(en)/Verzeichnisse du mit LUKS verschlüsselst?

Ingolf

**Comment by thoschworks** [comment]
Hallo @ingank 

> Danke für die ausführliche Antwort. Auch wenn du das Thema schon geschlossen hast, möchte ich dir doch gerne antworten.

Mache ihn wieder auf, wenn ich beim Senden dran denke.

> OK, ich kann mich vage daran erinnern, dass es ein paar 'WARNINGS' gab, doch als bei mir das Ergebnis in GRUB letztendlich zufriedenstellend war, hab ich nicht viel darauf gegeben. Wie gesagt, bei mir hat sich die Fehlerausgabe auf Warnings beschränkt.

Ist bei mir ja leider nicht bei Warnungen geblieben, auch wenn nicht `Error` oder `Fehler` dasteht.

irgendwas muss bei mir definitiv schief gegangen sein. Nach der Änderung konnte ich in den aus dem Menü mit \<c\> und \<e\> aufgerufenen Modi keinerlei Änderungen vornehmen, weil GRUB nicht mehr auf die Tastatur reagierte.

Nachdem ich die Änderungen ausgebaut und GRUB mit `update-grub` aktualisiert habe, funktionieren die Modi wieder.
 
> > Wenn das Passwort korrekt eingegeben ist, dann kann ich im Menü mit den Cursor-Tasten navigieren und mit  bzw.  in den jeweiligen Modus springen. Dort funktioniert die Tastatureingabe denn aber nicht mehr; also keine falsches Layout, sondern gar keine Reaktion auf die Tastaturanschläge.
> 
> Bedeutet das, dass nach einer erfolgreichen Entsperrung einer Partition Linux REBOOTET und du wieder im GRUB landest? Wenn dem so wäre, und GRUB in diesem Fall nicht 'normal' reagiert, dann wäre dies ein Sonderfall, der auf alle Fälle Wert wäre näher zu betrachten.

Nein, es er folgt kein Reboot.

Die Passwortabfrage wird mittlerweile von GRUB selbst durchgeführt; also nach dem Laden von GRUB, aber vor allen anderen Schritten, die bei einem nicht verschlüsselten System ablaufen:

1. GRUB wird geladen
2. GRUB erkennt anhand seiner Konfig, dass Verschlüsselung am Start ist
3. GRUB fragt die Passphrase ab
4. Stimmt die Passphrase, dann wird das root-Filesystem entschlüsselt
5. GRUB arbeitet die weiteren Schritte ab, als wäre das root-Filesystem nicht verschlüsselt.

> Danke auf alle Fälle für deine Bemühungen - ich würde gern mehr über LUKS erfahren.
> Kannst du mir bitte noch nähere Angaben über deine Distro machen und im Groben darüber, welche Partition(en)/Verzeichnisse du mit LUKS verschlüsselst?

Noch besser. Ich habe das Vorgehen dokumentiert:

- [Ubuntu Mate 20.04 auf Btrfs mit Verschlüsselung](https://wiki.thoschworks.de/thoschwiki/linux/ubuntumatebtrfsencrypted)

Grundlage ist der folgende - im den Quellen auch genannte - Artikel von @wmutschl (dort finden sich mehr Details zum Vorgehen):

- [Ubuntu 20.04 with btrfs-luks full disk encryption including /boot and auto-apt snapshots with Timeshift](https://www.mutschler.eu/linux/install-guides/ubuntu-btrfs/)

**Comment by ingank** [comment]
@thoschworks wie ich sehe, ist das Thema btrfs-luks kein Spaziergang, den man sich mal kurz zu Gemüte führt.

Nichtdestotrotz werde ich mir nach den beiden Anleitungen auch versuchen zuerst in einer VM ein entsprechendes Referenzsystem (nach) zu bauen. Bin mal gespannt - auch auf die Schmankerl, was GRUB betrifft...

[hier](../blob/btrfs-luks/how2_ubuntu-on-btrfs-luks.md) werde ich bis auf Weiteres meine Erkenntisse dokumentieren.

**Comment by thoschworks** [comment]
Moin @ingank, 

> @thoschworks wie ich sehe, ist das Thema btrfs-luks kein Spaziergang, den man sich mal kurz zu Gemüte führt.

Mmmh, Ansichtssache. Nach zweimal Durchlesen des Artikels von @wmutschl war _LUKS_ für mich streight forward. Mit _Btrfs_ hatte ich mich vorher schon angefreundet.

Dafür sind _GRUB_ und _Keyboard-Layouts_ für mich Bücher mit sieben Siegel und ein Alptraum… 😜 

 
> Nichtdestotrotz werde ich mir nach den beiden Anleitungen auch versuchen zuerst in einer VM ein entsprechendes Referenzsystem (nach) zu bauen. Bin mal gespannt - auch auf die Schmankerl, was GRUB betrifft...

Bin gespannt, was Du GRUB-mäßig erreichen kannst.

**Comment by ingank** [comment]
Kleines Update @thoschworks :
wie es ausschaut, können benutzerspezifische Module (also hoffentlich auch Tastaturlayoutverwurschtler) ins core-Image eingebunden werden. Das hat den Vorteil, dass keine /boot Partition für diese Module benötigt werden...
Sobald ich durch bin mit LUKS/Btrfs, kann ich mich diesem Ansatz widmen...
[Siehe](https://help-grub.gnu.narkive.com/tYopC4mg/grub2-possible-to-change-keyboard-layout-in-stage-1-5)
Bis denne

**Comment by ingank** [comment]
@thoschworks
nachdem ich mich tagelang durch google gekämpft habe, hatts heute geklappt...
hier vorläufige (persönliche) Konfig und Vorgehen:

* https://gist.github.com/ingank/ef986f8b30e77bf5ea23c0f72c0e23e2

werde meine Doku demnächst ändern...
Nachteil bis jetzt: wenn irgendeine Installation `grub-install` aufruft, ist die Einstellung wieder weg... mhmmm

schönes WE!

**Comment by ingank** [comment]
fce91a248d6bc7623c283a24199edd6152168c46, 1809bf59e60d68b999611e81e04ae44e1ae4ff0a
ich denke, das war's !?

**Comment by thoschworks** [comment]
Sorry, ich hatte mich mit dem Problem arrangiert und das Ganze aus den Augen verloren.
Mittlerweile bin ich auf Ubuntu Mate 22.04 und das Problem tritt nicht mehr auf.
Räume hier mal auf und schließe den Issue.
